### ISSUE TITLE
詢問關於更改為自己需要的BOT內容

### ISSUE THREAD

**Issue by ericti** [kkdai/LineBotTemplate#7]
您好，請問如果要嘗試更改為自定義的回話方式

是否要先 FORK 到自己的 Gibhub, 再改 main.go ?

我試著這樣做，改了 main.go 的第 56 行，我得到的反應仍然是

" OK  hello ! "

https://github.com/ericti/LineBotTemplate/blob/master/main.go

能否請您指導我正確的方式 ?

**Comment by kkdai** [comment]
如果當初你是使用 One-Click deploy 到 Heroku 的話，那麼你需要將你的變更改到 Heroku Server 去．
建議方式不要 Fork 原本的專案，而是去 clone Heroku 的專案代碼，

請直接到 Heroku 控制頁面

- [Heroku] 
- [App 列表]
- [Deploy]





![image](https://cloud.githubusercontent.com/assets/2252691/19879974/ad0ccec0-a033-11e6-8db9-a67371ae9062.png)

**Comment by kkdai** [comment]
Hi @ericti  

我做了段影片，希望能幫助到你．

https://www.youtube.com/watch?v=ckij73sIRik


主要的方式如下

1.  fork code to your repo
2. Change your custom code in your repo
3. add remote repo to your project.
